version: 2
project_name: tickettok

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - repository:
      owner: sns45
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/sns45/tickettok"
    description: "Terminal Kanban dashboard for managing multiple Claude Code agents via tmux"
    license: "MIT"
    dependencies:
      - name: tmux
    install: |
      bin.install "tickettok"
    test: |
      assert_match "tickettok", shell_output("#{bin}/tickettok version")

release:
  github:
    owner: sns45
    name: tickettok
